"""Confederation-bias correction for the Elo ratings (empirical-Bayes shrinkage).

Elo is zero-sum: a result only transfers points between the two opponents, so the total
rating *inside* a confederation is conserved regardless of that confederation's true global
level. Confederations are near-disconnected clusters joined by sparse "bridge" games
(inter-confederation friendlies / World Cup matches), so the global scale between clusters
is weakly anchored and drifts — weaker confederations accumulate inflated ratings against
weak regional opponents, and pure Elo cannot re-level them.
(refs: football-rankings.info 2022 "Is there a regional bias in the Elo rating?";
Szczeciński & Roatis 2022 arXiv:2201.00691; Lasek/Szlávik/Bhulai 2013; Bradley-Terry under
group sparsity arXiv:1111.5110; Peeters 2018 on squad value as a global anchor.)

The correction is an empirical-Bayes shrinkage toward a confederation re-leveling prior. Each
confederation has a base offset `delta[conf]` estimated from cross-confederation results only
(UEFA = reference 0). Each TEAM then receives a fraction of its confederation's offset that
shrinks with how well its rating is anchored across confederations:

    offset(team) = delta[conf(team)] * K / (n_cross(team) + K)

where `n_cross(team)` is the recency-weighted (8y half-life) count of the team's
cross-confederation games and `K` is the shrinkage scale. This is the standard EB weight
`tau^2/(tau^2+sigma_i^2)` with `sigma_i^2 ~ 1/n_cross`: a team that plays many intercontinental
games is well-anchored (small offset — trust its own rating); a regionally-isolated team has a
high-variance cross-confederation rating and falls back to its confederation prior (full
offset). Counts, not shares, so a side with 8 of 20 cross games is treated as better-anchored
than one with 2 of 4. (refs: James-Stein / Efron-Morris; empirical-Bayes for paired
comparisons arXiv:1807.09236; Glicko RD as a connectivity-aware uncertainty, Glickman 1999.)

Why apply before the squad-value blend: the globally-comparable squad value then further
corroborates the strong, well-resourced teams, so the correction never over-penalizes them.

Validation (scripts/calibrate_confed_offsets.py): a time-split, cross- vs within-confederation
stratified backtest on ~49k internationals. The shrinkage improves the out-of-sample CROSS-
confederation slice by ~+4.6% RPS (vs ~+3.2% for a flat per-confederation offset), and the
gain over the flat offset is significant after accounting for match dependence (Diebold-Mariano
HAC p≈0.004; team-cluster bootstrap 95% CI excludes 0). The within-confederation slice is
essentially untouched. The per-team offsets below are recomputed by that script.
"""

from __future__ import annotations

import numpy as np

from xresidual import wc2026_teams

# Continental-competition keywords -> confederation. Friendly / FIFA World Cup / Confederations
# Cup are cross-confederation and excluded (they are the bridge games the correction measures).
CONF_KW = {
    "UEFA": ["UEFA Euro", "UEFA Nations", "British Home", "Nordic Championship",
             "Central European", "Baltic"],
    "CONMEBOL": ["Copa América", "Copa America", "Copa Lipton", "Copa Newton", "Panamerican"],
    "CAF": ["African Cup", "African Nations", "CECAFA", "COSAFA", "Amílcar Cabral", "WAFU", "CEMAC"],
    "AFC": ["AFC Asian", "Asian Games", "AFF ", "Gulf Cup", "King's Cup", "Merdeka", "SAFF",
            "EAFF", "Arab Cup", "Korea Cup", "Southeast Asian", "Nehru Cup", "Asian Cup"],
    "CONCACAF": ["Gold Cup", "CONCACAF", "CFU Caribbean", "UNCAF", "CCCF", "NAFC"],
    "OFC": ["Oceania", "South Pacific", "Pacific Games", "Polynesia", "Melanesia"],
}
CONFEDERATIONS = ["UEFA", "CONMEBOL", "CONCACAF", "AFC", "CAF", "OFC"]  # UEFA = reference

# Empirical-Bayes shrinkage scale and the confederation base offsets (recency-weighted over all
# internationals; see module docstring + scripts/calibrate_confed_offsets.py).
SHRINK_K = 50.0
BASE_OFFSETS = {"UEFA": 0.0, "CONMEBOL": -41.1, "CONCACAF": -163.1,
                "AFC": -114.9, "CAF": -22.6, "OFC": -485.4}

# Confederation of each 2026 World Cup team (canonical names). Constant so the rating path
# needs no full-results parse; regenerated by the calibrate script.
WC_TEAM_CONF = {
    "Algeria": "CAF", "Argentina": "CONMEBOL", "Australia": "AFC", "Austria": "UEFA",
    "Belgium": "UEFA", "Bosnia & Herzegovina": "UEFA", "Brazil": "CONMEBOL", "Canada": "CONCACAF",
    "Cape Verde": "CAF", "Colombia": "CONMEBOL", "Croatia": "UEFA", "Curaçao": "CONCACAF",
    "Czech Republic": "UEFA", "DR Congo": "CAF", "Ecuador": "CONMEBOL", "Egypt": "CAF",
    "England": "UEFA", "France": "UEFA", "Germany": "UEFA", "Ghana": "CAF", "Haiti": "CONCACAF",
    "Iran": "AFC", "Iraq": "AFC", "Ivory Coast": "CAF", "Japan": "AFC", "Jordan": "AFC",
    "Mexico": "CONCACAF", "Morocco": "CAF", "Netherlands": "UEFA", "New Zealand": "OFC",
    "Norway": "UEFA", "Panama": "CONCACAF", "Paraguay": "CONMEBOL", "Portugal": "UEFA",
    "Qatar": "AFC", "Saudi Arabia": "AFC", "Scotland": "UEFA", "Senegal": "CAF",
    "South Africa": "CAF", "South Korea": "AFC", "Spain": "UEFA", "Sweden": "UEFA",
    "Switzerland": "UEFA", "Tunisia": "CAF", "Turkey": "UEFA", "USA": "CONCACAF",
    "Uruguay": "CONMEBOL", "Uzbekistan": "AFC",
}

# Effective per-team Elo offset = BASE_OFFSETS[conf] * K/(n_cross + K), precomputed for the 48
# World Cup teams. UEFA = 0 (reference). Regenerated by scripts/calibrate_confed_offsets.py.
TEAM_OFFSET = {
    "Algeria": -15.2, "Argentina": -18.8, "Australia": -56.3, "Austria": 0.0, "Belgium": 0.0,
    "Bosnia & Herzegovina": 0.0, "Brazil": -16.5, "Canada": -89.9, "Cape Verde": -17.6,
    "Colombia": -20.6, "Croatia": 0.0, "Curaçao": -137.8, "Czech Republic": 0.0, "DR Congo": -20.0,
    "Ecuador": -20.5, "Egypt": -13.9, "England": 0.0, "France": 0.0, "Germany": 0.0, "Ghana": -14.3,
    "Haiti": -123.6, "Iran": -63.3, "Iraq": -85.0, "Ivory Coast": -15.8, "Japan": -47.5,
    "Jordan": -69.6, "Mexico": -53.8, "Morocco": -13.6, "Netherlands": 0.0, "New Zealand": -231.3,
    "Norway": 0.0, "Panama": -95.1, "Paraguay": -22.1, "Portugal": 0.0, "Qatar": -56.7,
    "Saudi Arabia": -53.9, "Scotland": 0.0, "Senegal": -16.3, "South Africa": -15.9,
    "South Korea": -48.8, "Spain": 0.0, "Sweden": 0.0, "Switzerland": 0.0, "Tunisia": -13.5,
    "Turkey": 0.0, "USA": -63.6, "Uruguay": -19.0, "Uzbekistan": -79.0,
}


def conf_of_tournament(tournament: str) -> str | None:
    """Confederation a continental competition belongs to, or None for cross-confederation
    competitions (Friendly / World Cup / Confederations Cup — the bridge games)."""
    for conf, kws in CONF_KW.items():
        if any(k in tournament for k in kws):
            return conf
    return None


def apply_offsets(elo_ratings: dict, team_offset: dict = TEAM_OFFSET) -> dict:
    """Return a copy of `elo_ratings` (keyed by Elo-name) with each team's empirical-Bayes
    confederation offset added. Teams not in `team_offset` are returned unchanged."""
    out = dict(elo_ratings)
    for team, off in team_offset.items():
        en = wc2026_teams.elo_name(team)
        if en in out:
            out[en] = out[en] + off
    return out


# ---- calibration (used by scripts/calibrate_confed_offsets.py; not the hot path) ----------

def confederation_map(results) -> dict:
    """team -> confederation, by majority of the team's continental-competition appearances.
    `results` is the raw international-results frame (home_team/away_team/tournament)."""
    from collections import Counter
    votes: dict[str, Counter] = {}
    for r in results.itertuples(index=False):
        c = conf_of_tournament(r.tournament)
        if not c:
            continue
        for tm in (r.home_team, r.away_team):
            votes.setdefault(tm, Counter())[c] += 1
    return {tm: cc.most_common(1)[0][0] for tm, cc in votes.items()}


def cross_counts(calib, team_conf: dict, asof, halflife_years: float = 8.0) -> dict:
    """team -> recency-weighted count of cross-confederation games (the EB anchoring strength)."""
    ch = calib["home_team"].map(team_conf); ca = calib["away_team"].map(team_conf)
    cross = (ch != ca).values & ch.notna().values & ca.notna().values
    age = ((np.datetime64(asof) - calib["date"].values.astype("datetime64[D]"))
           .astype("timedelta64[D]").astype(float) / 365.25)
    rw = 0.5 ** (np.clip(age, 0, None) / halflife_years)
    home = calib["home_team"].values; away = calib["away_team"].values
    out: dict[str, float] = {}
    for k in np.nonzero(cross)[0]:
        out[home[k]] = out.get(home[k], 0.0) + rw[k]
        out[away[k]] = out.get(away[k], 0.0) + rw[k]
    return out


def fit_base_offsets(calib, team_conf: dict, counts: dict, asof, k: float = SHRINK_K,
                     halflife_years: float = 8.0, iters: int = 300, lr: float = 0.6) -> dict:
    """Estimate the per-confederation base offsets under the EB shrinkage weight
    w(team) = k/(n_cross(team)+k), by iteratively zeroing each confederation's
    importance-and-recency-weighted cross-confederation surprise. UEFA pinned to 0."""
    b = calib.copy()
    b["ch"] = b["home_team"].map(team_conf); b["ca"] = b["away_team"].map(team_conf)
    b = b.dropna(subset=["ch", "ca"]); b = b[b["ch"] != b["ca"]]
    age = ((np.datetime64(asof) - b["date"].values.astype("datetime64[D]"))
           .astype("timedelta64[D]").astype(float) / 365.25)
    rw = b["imp"].values * 0.5 ** (np.clip(age, 0, None) / halflife_years)
    dr = b["dr_eff"].values
    w = np.where(b["goal_diff"].values > 0, 1.0, np.where(b["goal_diff"].values == 0, 0.5, 0.0))
    hi = np.array([CONFEDERATIONS.index(c) for c in b["ch"]])
    ai = np.array([CONFEDERATIONS.index(c) for c in b["ca"]])
    sh = np.array([k / (counts.get(t, 0.0) + k) for t in b["home_team"]])
    sa = np.array([k / (counts.get(t, 0.0) + k) for t in b["away_team"]])
    delta = np.zeros(len(CONFEDERATIONS))
    for _ in range(iters):
        dd = delta[hi] * sh - delta[ai] * sa
        we = 1.0 / (1.0 + 10 ** (-(dr + dd) / 400.0))
        deriv = np.log(10) / 400.0 * we * (1 - we)
        grad = np.zeros(len(CONFEDERATIONS)); wsum = np.zeros(len(CONFEDERATIONS))
        np.add.at(grad, hi, rw * sh * (w - we)); np.add.at(wsum, hi, rw * deriv * sh * sh)
        np.add.at(grad, ai, -rw * sa * (w - we)); np.add.at(wsum, ai, rw * deriv * sa * sa)
        step = lr * grad / np.maximum(wsum, 1e-9)
        step[0] = 0.0
        delta += step; delta -= delta[0]
    return dict(zip(CONFEDERATIONS, delta))


def team_offsets(base: dict, counts: dict, conf_map: dict = WC_TEAM_CONF,
                 k: float = SHRINK_K) -> dict:
    """Effective per-team offset = base[conf] * k/(n_cross + k), keyed by canonical team name."""
    out = {}
    for team, conf in conf_map.items():
        en = wc2026_teams.elo_name(team)
        out[team] = base.get(conf, 0.0) * k / (counts.get(en, 0.0) + k)
    return out
